# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

plugins:
  - jekyll-paginate

# Setup
title:               Xiaotong Ni's Blog
tagline:             'Placeholder'
description:         'About quantum computing and machine learning'
url:                 xiaotongni.github.io
baseurl:             'https://xiaotongni.github.io/'
paginate:            5

# About/contact
author:
  name:              Xiaotong Ni
  # url:               https://twitter.com/mdo
  email:             xiaotong.ni@gmail.com

# Custom vars
version:             1.0.0
